/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sFm94TFtKwf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Manrope } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

manrope({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
export function Tarjeta() {
  return (
    <Card className="w-full mx-auto max-w-[430px]">
      <CardHeader className="pb-0">
        <img src="/foto1.jpg" />
        <CardTitle className="text-xl font-bold">
          Terreno en Valle Grande
        </CardTitle>
        <CardDescription>
          Hermoso terreno con vista a la naturaleza. Perfecto para tu hogar
          soñado.
        </CardDescription>
      </CardHeader>
      <CardContent className="pt-0">
        <div className="grid gap-1.5 text-sm">
          <div className="flex items-center">
            <UserIcon className="w-4 h-4 mr-1.5" />
            Propietario: Juan Pérez
          </div>
          <div className="flex items-center">
            <HomeIcon className="w-4 h-4 mr-1.5" />
            Estado: Disponible
          </div>
          <div className="flex items-center">
            <MapPinIcon className="w-4 h-4 mr-1.5" />
            Ubicación: Valle Grande, Cajamarca
          </div>
          <div className="flex items-center">
            <InfoIcon className="w-4 h-4 mr-1.5" />
            Detalles: Terreno de 500m² con acceso a servicios básicos.
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <div className="flex w-full justify-between items-end gap-2">
          <div className="text-2xl font-semibold">S/.28,000</div>
          <Button className="bg-[#2962FF] py-2 px-7 rounded-lg text-white">
            <Link href={"/detalles"}>Detalles </Link>
          </Button>
        </div>
      </CardFooter>
    </Card>
  );
}

function HomeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}

function InfoIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  );
}

function MapPinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  );
}

function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
